spring.application.name=api-gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: show-service
          uri: http://localhost:8081
          predicates:
            - Path=/shows/**

        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/booking/**